import type { Metadata } from "next";
import { Oswald } from 'next/font/google';
import "./globals.css";

const roboto_init = Oswald({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Hair You Go",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
